### ISSUE TITLE
She is broken

### ISSUE THREAD

**Issue by Rudis1261** [zerkz/HOTSBA#7] opened 2017-02-20 14:46 UTC
I have now tried both the Mac and Windows version:

Error: Command failed: 4294967295 System.AggregateException: One or more errors occurred. ---> System.Exception: Couldn't acquire lock, is another instance running at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut) at Squirrel.UpdateManager.b__31_0() at System.Threading.Tasks.Task`1.InnerInvoke() at System.Threading.Tasks.Task.Execute() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Squirrel.UpdateManager.d__7.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Squirrel.Update.Program.d__7.MoveNext() --- End of inner exception stack trace --- at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) at System.Threading.Tasks.Task`1.get_Result() at Squirrel.Update.Program.executeCommandLine(String[] args) at Squirrel.Update.Program.main(String[] args) at Squirrel.Update.Program.Main(String[] args) ---> (Inner Exception #0) System.Exception: Couldn't acquire lock, is another instance running at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut) at Squirrel.UpdateManager.b__31_0() at System.Threading.Tasks.Task`1.InnerInvoke() at System.Threading.Tasks.Task.Execute() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Squirrel.UpdateManager.d__7.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Squirrel.Update.Program.d__7.MoveNext()<---

**Comment by zerkz** [comment] 2017-02-20 20:33
thanks for opening an issue. I'll see what's going on.

**Comment by Rudis1261** [comment] 2017-02-21 05:31
Awesome thank you, quite keen to see it in action :-)

**Comment by zerkz** [comment] 2017-02-23 17:25
@drpain sorry, I've been pretty bogged down with real life work. I did identify an issue, and I'll try to fix it tonight.

**Comment by Rudis1261** [comment] 2017-02-23 17:42
100% thank you Zack. I know how it goes

**Comment by zerkz** [comment] 2017-02-26 15:25
@drpain found the issue. It was Lucio's accent in his u. HOTSLOGS stores the image url with that accent, which is fine because most browsers could interpret it, but not my program 👍 

Fix is pushed and should be available soon once i do the release.

released here: https://github.com/zerkz/HOTSBA/releases/tag/v1.0.6

**Comment by Rudis1261** [comment] 2017-02-26 17:05
Awesome thanks for the effort Zack, downloading it now ;-)

**Comment by zerkz** [comment] 2017-02-26 20:36
@drpain did it work?

**Comment by Rudis1261** [comment] 2017-02-27 05:59
Hi Zack,

No sadly still getting the same exception. Complaining about multiple exceptions. 

I primarily use Windows for my gaming rig if that helps find the issue.

Kind regards,
Rudi

**Comment by zerkz** [comment] 2017-02-27 06:58
Have you tried uninstalling completely if you haven't already, and make
sure your firewalls are turned off,or run as admin?

**Comment by Rudis1261** [comment] 2017-02-27 07:01
I did uninstall it and reinstall 1.0.5. I also tried running as admin but still had the same issue.

I will try explicitly adding a exception for the exe, but it's only a windows firewall.

I will let you know once I run it tonight

**Comment by zerkz** [comment] 2017-02-27 07:05
Latest version is 1.0.6.

**Comment by Rudis1261** [comment] 2017-02-27 09:40
I will check and confirm. I can in the meanwhile confirm the Mac version is working now :-) Will check tonight and let you know about Windows

**Comment by Rudis1261** [comment] 2017-02-27 14:29
Sorry yeah I was using 1.0.6 all along. Still getting the following error:

```
Error: Command failed: 4294967295 System.AggregateException: One or more errors occurred. ---> System.Exception: Couldn't acquire lock, is another instance running at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut) at Squirrel.UpdateManager.b__31_0() at System.Threading.Tasks.Task`1.InnerInvoke() at System.Threading.Tasks.Task.Execute() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Squirrel.UpdateManager.d__7.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Squirrel.Update.Program.d__7.MoveNext() --- End of inner exception stack trace --- at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) at System.Threading.Tasks.Task`1.get_Result() at Squirrel.Update.Program.executeCommandLine(String[] args) at Squirrel.Update.Program.main(String[] args) at Squirrel.Update.Program.Main(String[] args) ---> (Inner Exception #0) System.Exception: Couldn't acquire lock, is another instance running at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut) at Squirrel.UpdateManager.b__31_0() at System.Threading.Tasks.Task`1.InnerInvoke() at System.Threading.Tasks.Task.Execute() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Squirrel.UpdateManager.d__7.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Squirrel.Update.Program.d__7.MoveNext()<---
```

**Comment by Rudis1261** [comment] 2017-02-27 14:29
Tried adding an application exception to the firewall, and running as administrator

**Comment by zerkz** [comment] 2017-02-27 16:16
Ah ok, I've seen that error many times, but its not too helpful. I'll see if I can test on my Windows machine tonight, and maybe improve the error reporting.

**Comment by Rudis1261** [comment] 2017-02-27 17:25
Awesome thanks Zack!

**Comment by zerkz** [comment] 2017-03-01 16:14
@drpain , i have now installed it cleanly (and it worked) on two different windows machines that I have. I have no ETA on whenever I can get the improved logging in, but I'm at a loss at what could be causing this.

**Comment by Rudis1261** [comment] 2017-03-01 17:16
No worries man, the effort is appreciated. But I don't want to be a bother

**Comment by zerkz** [comment] 2017-03-05 06:11
@drpain i pushed up a fix. This is seems to be a common mistake that I was documented in Electron's docs well after I first released HOTSBA. Really hope this does the trick. Please uninstall the old version completely before installing this new one.

**Comment by zerkz** [comment] 2017-03-05 06:18
@drpain  https://github.com/zerkz/HOTSBA/releases/tag/1.0.7

**Comment by zerkz** [comment] 2017-03-13 16:23
@drpain lemme know if you had a chance to test this out so I can close the issue. Thanks!

**Comment by Rudis1261** [comment] 2017-03-25 09:53
Hi @zerkz, sorry for only testing now. It's been a bit hectic my side. Sorry to be bearer of bad news. 1.0.7 still borks. 

http://i.imgur.com/mx8CHNB.jpg

I installed is as an admin if that helps. It's broke on update as part of the installation process

**Comment by zerkz** [comment] 2017-03-27 03:39
@drpain did you say its breaking on update? did you try uninstalling and then reinstalling the newest install? 

I'm at a loss as I've tested this on a few windows machines.

**Comment by Rudis1261** [comment] 2017-03-27 04:29
I will try again tonight and report back. Is there any dependancies I might be missing?

**Comment by zerkz** [comment] 2017-05-07 19:09
@drpain there shouldn't be. I'm going to close this issue as I'm not sure how to fix it as i cannot reproduce.

**Closed as completed by zerkz** 2017-05-07 19:09 UTC
